### PR TITLE
Write region data to beacons

### PR DESCRIPTION
**Pull request by anulman**
We selected this plugin for a client project, and will need to implement functions like `writeProximityUUID`, `writeMajor`, and `writeMinor`.

We selected this plugin as it seemed among the more mature & active offerings available. Was hoping to contribute our work back to the community.

We should be finished by end of week for Android and, if you will consider merging, will follow up with iOS shortly thereafter.

Please do let me know if you are open to merging this PR. If so, would appreciate any feedback re: style / implementation that may prevent a merge in the interim.

### CODE REVIEW

**Comment by anulman** [comment]
Delayed due to https://github.com/Estimote/Android-SDK/issues/112

**Comment by anulman** [comment]
Confirmed working on Android devices. /cc @divineprog @kdzwinel

**Comment by mazekeeper** [comment]
Dear Anulman, we're absolutely into merging code contributions like yours, it looks well-structured and with clear contribs. Sadly enough, time it not on our side in this and we have currently quite a heavy workload in our core business with the studio software, and have put many of the related feature tracks on hold for this quarter. We promise we haven't forgot about you and are looking forward to pick this up shortly for the benefit of better software for all!

**Comment by anulman** [comment]
Thanks @mazekeeper. I'll keep working on our fork then (several clients are using it already); would it be helpful if I opened PRs for new features / a general one against our master branch?

**Comment by divineprog** [comment]
@anulman Thank you very much, yes please open new pull requests. Merging your work is in the pipeline, will start looking into updating the plugin to latest Estimote SDKs in the end of this month and also have a look at your pull requests. Best regards, Mikael

**Comment by anulman** [comment]
Thanks @divineprog. I'll actually be touching the new SDKs in the next week or so, namely rewriting the `writeProximityUUID`, `writeMajor`, and `writeMinor` methods in Android and bringing feature parity to iOS.

Do you have any other features that may make sense to include with this package? And have you started looking at plugin tests yet, to prevent regressions?

**Comment by divineprog** [comment]
@anulman It is fantastic if you can bring the Android SDK up to date. Have not written structured tests, do you have any suggestions? An app that performs tests? I have used the example app for manual testing, and done some automated testing using JavaScript snippets evaluated from Evothings Studio. Regarding future development, one idea is to make a separate repository for example apps (e.g. ponegap-estimotebeacons-examples), because when you install the plugin, it brings in the example code as well, which is not an ideal situation. Have not found any workaround for this, do you have any ideas?

**Comment by divineprog** [comment]
@anulman Finally merged your pull request. Sorry for the delay. Many thanks for the contribution!

**Pull request merged**
